### ISSUE TITLE
Double appel

### ISSUE THREAD

**Issue by aiwanesk** [AdrienG88/P2_GEOFFROY_Adrien#2]
https://github.com/AdrienG88/P2_GEOFFROY_Adrien/blob/c4e8d4afa25f98aa1bf3b3c7a4c1d8889cbb6a1a/P2_01_scrape_bookstoscrape_website.py#L140

Pourquoi faire deux appels à la suite à la même méthode?

**Comment by AdrienG88** [comment]
J'ai enlevé les doubles appels, tout fonctionne.
