### ISSUE TITLE
Ajout de print

### ISSUE THREAD

**Issue by aiwanesk** [AdrienG88/P2_GEOFFROY_Adrien#4]
https://github.com/AdrienG88/P2_GEOFFROY_Adrien/blob/c4e8d4afa25f98aa1bf3b3c7a4c1d8889cbb6a1a/P2_01_scrape_bookstoscrape_website.py#L25

Print ce que tu ajoutes et le contenu de la liste au fur et à mesure des itérations. Je pense que le soucis est dans cette partie.

**Comment by AdrienG88** [comment]
Merci pour ta réponse, j'ai compris grâce à toi d'où vient le problème. Etant donné que j'assigne comme valeur à la variable cat_links la fonction scrape_categories_urls, cette valeur est successivement une liste [url0], [url0, url1], [url0, url1, url2], etc. Valeurs successives qui sont utilisées dans la fonction suivante, normal. Je vais m'efforcer de trouver le moyen de prendre uniquement la dernière valeur retournée par scrape_categories_urls pour exécuter le reste du script et ça devrait être bon.

**Comment by AdrienG88** [comment]
Problem solved
